### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'max_value'

### ISSUE THREAD

**Issue by sdrabb** [psudowe/parse27k_tools#2]
i got this error when i'm trying to build crop. how i can solve it?
**processing split:  train
Traceback (most recent call last):
  File "./preprocess_dataset.py", line 250, in <module>
    main(args)
  File "./preprocess_dataset.py", line 208, in main
    crops, labels, pids = preprocess_examples(args, examples, include_mirrors=include_mirrors)
  File "./preprocess_dataset.py", line 137, in preprocess_examples
    with ProgressBar(max_value=len(examples)) as progress:
TypeError: __init__() got an unexpected keyword argument 'max_value**'

**Comment by sdrabb** [comment]
i solve by changing this two line:
** line 137**  ---->         `#with ProgressBar(max_value=len(examples)) as progress:
`** line 139**  ---->         `#with ProgressBar(max_value=len(examples)) as progress:
**and `by commenting the variables associated by theese with**
here the new file attached
[preprocess_dataset.py.zip](https://github.com/psudowe/parse27k_tools/files/669320/preprocess_dataset.py.zip)
